version: '3.9'
services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME}:${APP_VERSION}
    env_file: .env
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_AUTHMODE: ${MAIL_AUTHMODE}
      MAIL_USER: ${MAIL_USER}
      MAIL_ADMIN: ${MAIL_ADMIN}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    working_dir: /var/www/html/
    volumes:
      - storage:/var/www/html/storage
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      - internal
    ports:
      - ${APP_PORT}:80
    depends_on:
      - db

  db:
    image: mariadb:10.8
    # ports:
    #   - 3306:3306
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - internal

networks:
  internal:

volumes:
  storage:
  dbdata: