version: '3.8'
services:

  app:
    build: ./
    ports:
      - 80:80
      - 443:443
    working_dir: /
    volumes:
      - .//:/app
    #      - ./docker-files/backend/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  db:
    image: mariadb:10.8
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lbase10
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: somos
      MYSQL_USER: somos
    volumes:
      - ./backend/docker-files/db/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
